name: Live Stream 24/7 Relay

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install ffmpeg -y

      - name: Iniciar Transmissão da Live
        run: |
          ffmpeg \
              -re -stream_loop -1 -i "${{ secrets.VIDEO_URL }}" \
              -c copy \
              -f flv "${{ secrets.RTMP_URL }}/${{ secrets.STREAM_KEY }}"
